services:
  znuny-app:
    build: .
    container_name: znuny-app
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - znuny-data:/opt/znuny

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: znuny
      MYSQL_PASSWORD: znuny_password
    command: --max_allowed_packet=128M --innodb_log_file_size=256M
    volumes:
      - db-data:/var/lib/mysql

volumes:
  znuny-data:
  db-data:
